server:
  port: 8001
dubbo:
  application:
    name: provider
  registry:
    #address: multicast://224.5.6.7:1234
    address: zookeeper://localhost:2181
    timeout: 6000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.xkx.dubbo.service